.gitignore
README.md
data/example_output/example_hits_output.csv
data/example_output/example_profile_output.csv
data/experiment_ids.txt
docs/coursework_task.odt
docs/coursework_task.pdf
infra/ansible/all.yaml
infra/ansible/cloud-init.tmpl.yml
infra/ansible/cnc-local.yaml
infra/ansible/cnc.yaml
infra/ansible/full.yaml
infra/ansible/host.yaml
infra/ansible/inventory.ini
infra/ansible/nfs_clients.yaml
infra/ansible/roles/all_node_exporter/files/node_exporter.service
infra/ansible/roles/all_node_exporter/tasks/main.yml
infra/ansible/roles/all_pipeline_logging/tasks/logrotate.yaml
infra/ansible/roles/all_pipeline_logging/tasks/main.yml
infra/ansible/roles/all_pipeline_logging/tasks/pipeline_logging_dirs.yaml
infra/ansible/roles/all_pipeline_logging/templates/protien_pipeline.logrotate.j2
infra/ansible/roles/archive/host_configure_nfs/files/exports.j2
infra/ansible/roles/archive/host_configure_nfs/tasks/main.yaml
infra/ansible/roles/archive/host_nfs_populator/tasks/host_clone_git.yaml
infra/ansible/roles/archive/host_nfs_populator/tasks/host_download_datasets.yaml
infra/ansible/roles/archive/host_nfs_populator/tasks/host_download_datasets.yaml.save
infra/ansible/roles/archive/host_nfs_populator/tasks/host_download_datasets.yaml.save.1
infra/ansible/roles/archive/host_nfs_populator/tasks/host_install_hhsuite.yaml
infra/ansible/roles/archive/host_nfs_populator/tasks/host_install_s4pred.yaml
infra/ansible/roles/archive/host_nfs_populator/tasks/main.yaml
infra/ansible/roles/archive/host_pipeline/tasks/main.yaml
infra/ansible/roles/archive/host_redis/tasks/main.yaml
infra/ansible/roles/archive/host_storage/files/exports.j2
infra/ansible/roles/archive/host_storage/tasks/main.yaml
infra/ansible/roles/archive/worker_configure_celery/tasks/main.yaml
infra/ansible/roles/archive/worker_configure_celery/templates/celery-daemon.service.j2
infra/ansible/roles/archive/worker_configure_celery/templates/celeryconfig.py.j2
infra/ansible/roles/archive/worker_configure_nfs/tasks/main.yaml
infra/ansible/roles/archive/worker_pipeline/tasks/main.yaml
infra/ansible/roles/archive/worker_python/tasks/main.yaml
infra/ansible/roles/archive/worker_storage/tasks/main.yaml
infra/ansible/roles/client_configure_nfs/tasks/main.yaml
infra/ansible/roles/cnc/tasks/main.yaml
infra/ansible/roles/common/tasks/local.yaml
infra/ansible/roles/common/tasks/main.yml
infra/ansible/roles/common/tasks/tools.yaml
infra/ansible/roles/common/tasks/update.yaml
infra/ansible/roles/host_configure_minio/files/generate_certs.sh
infra/ansible/roles/host_configure_minio/tasks/main.yml
infra/ansible/roles/host_configure_minio/tasks/minio.yaml
infra/ansible/roles/host_configure_minio/templates/mc_config.json.j2
infra/ansible/roles/host_configure_minio/templates/minio.j2
infra/ansible/roles/host_configure_redis/tasks/main.yaml
infra/ansible/roles/host_database/files/populate_uniprot_database.py
infra/ansible/roles/host_database/tasks/configure_pg_hba.yml
infra/ansible/roles/host_database/tasks/create_host_user.yml
infra/ansible/roles/host_database/tasks/create_pipeline_database.yml
infra/ansible/roles/host_database/tasks/download_uniprot.yml
infra/ansible/roles/host_database/tasks/initialise_postgres_database.yml
infra/ansible/roles/host_database/tasks/main.yml
infra/ansible/roles/host_database/tasks/populate_database.yml
infra/ansible/roles/host_database/tasks/remove_uniprot_download.yml
infra/ansible/roles/host_files/tasks/main.yml
infra/ansible/roles/host_logging/files/dashboards/pipeline_grafana_dashboard.json
infra/ansible/roles/host_logging/files/provisioning/dashboards.yaml
infra/ansible/roles/host_logging/files/provisioning/datasource-prometheus.yaml
infra/ansible/roles/host_logging/tasks/host_grafana.yaml
infra/ansible/roles/host_logging/tasks/host_prometheus.yaml
infra/ansible/roles/host_logging/tasks/main.yml
infra/ansible/roles/host_logging/templates/prometheus.yml.j2
infra/ansible/roles/host_logging/templates/rules.yml.j2
infra/ansible/roles/host_python_dependencies/tasks/main.yaml
infra/ansible/roles/openmpi/files/mca-params.conf
infra/ansible/roles/openmpi/tasks/main.yml
infra/ansible/roles/python312/tasks/main.yml
infra/ansible/roles/reboot/tasks/main.yml
infra/ansible/roles/seconddisk/tasks/main.yml
infra/ansible/roles/storage_configure_nfs/files/exports.j2
infra/ansible/roles/storage_configure_nfs/tasks/main.yaml
infra/ansible/roles/storage_logging/tasks/main.yml
infra/ansible/roles/storage_logging/templates/storage_pipeline.logrotate.j2
infra/ansible/roles/storage_nfs_populator/tasks/install_build_tools.yaml
infra/ansible/roles/storage_nfs_populator/tasks/main.yaml
infra/ansible/roles/storage_nfs_populator/tasks/storage_clone_git.yaml
infra/ansible/roles/storage_nfs_populator/tasks/storage_download_datasets.yaml
infra/ansible/roles/storage_nfs_populator/tasks/storage_install_hhsuite.yaml
infra/ansible/roles/storage_nfs_populator/tasks/storage_install_s4pred.yaml
infra/ansible/roles/worker_configure_celery/tasks/main.yaml
infra/ansible/roles/worker_configure_celery/tasks/ops.yml
infra/ansible/roles/worker_configure_celery/tasks/worker_celery.yaml
infra/ansible/roles/worker_configure_celery/templates/celery-daemon.service.j2
infra/ansible/roles/worker_configure_celery/templates/celeryconfig.py.j2
infra/ansible/roles/worker_python_dependencies/tasks/main.yaml
infra/ansible/storage.yaml
infra/ansible/workers.yaml
infra/terraform/build_cluster/all.yaml
infra/terraform/build_cluster/bootstrap/README.md
infra/terraform/build_cluster/bootstrap/bootstrap.sh
infra/terraform/build_cluster/bootstrap/inventory.ini
infra/terraform/build_cluster/bootstrap/provision_cluster.sh
infra/terraform/build_cluster/check_worker_logs.sh
infra/terraform/build_cluster/cloud-init.tmpl.yml
infra/terraform/build_cluster/cnc-local.yaml
infra/terraform/build_cluster/cnc.yaml
infra/terraform/build_cluster/full.yaml
infra/terraform/build_cluster/generate_inventory.py
infra/terraform/build_cluster/generate_inventory_example.py
infra/terraform/build_cluster/host.yaml
infra/terraform/build_cluster/main.tf
infra/terraform/build_cluster/main_backup.tf.bak
infra/terraform/build_cluster/outputs.tf
infra/terraform/build_cluster/providers.tf
infra/terraform/build_cluster/roles/cnc/tasks/main.yaml
infra/terraform/build_cluster/roles/common/tasks/local.yaml
infra/terraform/build_cluster/roles/common/tasks/main.yml
infra/terraform/build_cluster/roles/common/tasks/tools.yaml
infra/terraform/build_cluster/roles/common/tasks/update.yaml
infra/terraform/build_cluster/roles/host_redis/tasks/main.yaml
infra/terraform/build_cluster/roles/host_storage/files/exports.j2
infra/terraform/build_cluster/roles/host_storage/tasks/main.yaml
infra/terraform/build_cluster/roles/openmpi/files/mca-params.conf
infra/terraform/build_cluster/roles/openmpi/tasks/main.yml
infra/terraform/build_cluster/roles/python312/tasks/main.yml
infra/terraform/build_cluster/roles/reboot/tasks/main.yml
infra/terraform/build_cluster/roles/seconddisk/tasks/main.yml
infra/terraform/build_cluster/roles/worker_celery/tasks/main.yaml
infra/terraform/build_cluster/roles/worker_celery/templates/celery-daemon.service.j2
infra/terraform/build_cluster/roles/worker_pipeline/tasks/main.yaml
infra/terraform/build_cluster/roles/worker_python/tasks/main.yaml
infra/terraform/build_cluster/roles/worker_storage/tasks/main.yaml
infra/terraform/build_cluster/variables.tf
infra/terraform/build_cluster/versions.tf
infra/terraform/build_cluster/workers.yaml
keys/lecturer_key.pub
keys/test-authorized-keys.sh
original_scripts_celery/celeryApp.py
original_scripts_celery/pipeline_tasks.py
original_scripts_celery/results_parser_tasks.py
original_scripts_celery/select_ids_tasks.py
scripts/celery.BAK/Copytasks.py
scripts/celery.BAK/celeryconfig.py
scripts/celery.BAK/run_pipeline_host.py
scripts/celery.BAK/tasks.py
scripts/celery/Copytasks.py
scripts/celery/aggregate_results.py
scripts/celery/celeryconfig.py
scripts/celery/metrics.py
scripts/celery/pipeline_logging.py
scripts/celery/pipeline_logging_manual.py
scripts/celery/results_parser.py
scripts/celery/run_pipeline_host.py
scripts/celery/select_ids.py
scripts/celery/tasks.py
scripts/celery/tasks_no_retry.py
scripts/celery/tasks_rety_test.py
scripts/celery/test_run_pipeline.py
scripts/helperScripts.BAK/metrics.py
scripts/helperScripts.BAK/pipeline_logging.py
scripts/helperScripts.BAK/pipeline_logging_manual.py
scripts/helperScripts.BAK/results_parser.py
scripts/helperScripts.BAK/select_ids.py
scripts/helperScripts/fasta_diagnostic.py
scripts/planned_metrics.md
src/pipeline_example/hhr_parse.out
src/pipeline_example/test.fa
src/pipeline_example/tmp.a3m
src/pipeline_example/tmp.fas
src/pipeline_example/tmp.hhr
src/pipeline_example/tmp.horiz
src/pipeline_example/tr|A0A087WV00|A0A087WV00_HUMAN_parse.out
src/pipeline_script.py
src/results_parser.py
src/select_ids.py
